### ISSUE TITLE
Issues with the Voidwoken fight in Wrecker's Cave, the one overlooking the Mordus fight arena

### ISSUE THREAD

**Issue by Valmar33** [BlueFeuer/Divinity-Combat-Overhaul#7]
The Voidwoken would normally web party members and then dump them in set locations elsewhere in Wrecker's Cave.

These never use their webbing ability, and rather just attack the party until they're dead.

**Comment by BlueFeuer** [comment]
This took a while to figure out what was going on and fix. I haven't been able to test the fix, but it should work now.

**Comment by Valmar33** [comment]
Not fixed, unfortunately.
