### ISSUE TITLE
Voidwoken Curse ability not being cured by Bless

### ISSUE THREAD

**Issue by Valmar33** [BlueFeuer/Divinity-Combat-Overhaul#8]
In the Voidwoken fight after you pick up the ring needed by the quest Lost and Found, the Voidwoken will cast Curse, but Bless won't cancel it out, but rather exist alongside it.

**Comment by BlueFeuer** [comment]
I assume this was with the blessing skill from Thaumaturgy - Interaction should be fixed.

**Comment by Valmar33** [comment]
Should have clarified that this is with vanilla Bless. Sorry.
